### ISSUE TITLE
can't build as-sis (hardcoded paths of static libs)

### ISSUE THREAD

**Issue by sl1pkn07** [m4tthi4s/vukextract#1]
Hi, i tried build you program. but fails as-sis on my archlinux:

```
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/vukextract]|
└───╼  make
gcc -static -Wall -Werror    -c -o vukextract.o vukextract.c
gcc -static -Wall -Werror -o vukextract vukextract.o -L../libgcrypt-1.7.6/src/.libs -lgcrypt -L../libgpg-error-1.27/src/.libs -lgpg-error
/usr/bin/ld: no se puede encontrar -lgcrypt
/usr/bin/ld: no se puede encontrar -lgpg-error
collect2: error: ld devolvió el estado de salida 1
make: *** [Makefile:15: vukextract] Error 1
```

then I make some changes in the Makefile for fix it, and use shared libraries instead of static libs

~~~patch
diff --git a/Makefile b/Makefile
index 5ec0325..3667f8c 100644
--- a/Makefile
+++ b/Makefile
@@ -1,9 +1,8 @@
-CC = gcc -static -Wall -Werror
-#CC = gcc -g -static -Wall -Werror
-#CC = gcc -Wall -Werror
+CC = gcc
+#CC = gcc -g
 
-LDFLAGS = -L../libgcrypt-1.7.6/src/.libs -lgcrypt \
-					-L../libgpg-error-1.27/src/.libs -lgpg-error
+CFLAGS	+=	-fPIC -Wall -Werror $(shell libgcrypt-config --cflags)
+LDFLAGS	+=	$(shell libgcrypt-config --libs)
 
 src = vukextract.c 
 obj = $(src:.c=.o)
@@ -12,7 +11,7 @@ all: vukextract
 
 
 vukextract: $(obj)
-	$(CC) -o $@ $^ $(LDFLAGS)
+	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS)
 
 
 clean:
~~~

if you are OK with this changes, I can make a PR for merge this changes

greetings

**Comment by m4tthi4s** [comment]
I am using the static-linking for providing the pre-build files on the release page. So the binaries will be compatible if you have other versions of libgcrypt/libgpg installed on your computer, which might happen quite often if you frequently update.
You can create a PR if you want to...
Thank you and greetings.

I think the best compromise would be to split shared and static building into separate build targets like:

    all: vukextract

    #normal shared linking
    vukextract: $(obj)

    #static linking for prebuild binaries
    static: $(obj)
        $(CC) -o $@ $^ $(LDFLAGS)
